### ISSUE TITLE
[Request] Move windows to specific virtual desktop with shortcut

### ISSUE THREAD

**Issue by sonal-keshav** [sdias/win-10-virtual-desktop-enhancer#1]
Move current active window to a specific virtual desktop via a key shortcut (shift + alt + [num]) for example.

**Comment by sdias** [comment]
This should be possible with the library I'm using. The issue is that I'm working with two different versions of that library, and they have different features between them (moving windows between desktops is only available in the newer version). 

I'm working with these two versions because the one that actually works for your system depends on the version of the VS 2015 C++ runtime you have installed, and the version on Microsoft's site differs from the version windows update installs for Windows 10...

In addition to this, I can only seem to get the old version of the library to work on my system, so I'm having a hard time implementing this. I'm going to see what can I do about it.

**Comment by sonal-keshav** [comment]
I can help in testing with the newer version of the library.

I'm assuming that [this](https://www.microsoft.com/en-us/download/details.aspx?id=48145) is the newer version of the library?

I can also provide access to a Windows VM hosted on Azure if that makes things easy.

**Comment by sdias** [comment]
Thanks, but I'd rather try to get it to work on my personal system first. This is such a small project that I don't think it warrants the usage of other resources like your VM and your time. :) Thanks for the offer though.

**Comment by sdias** [comment]
Just wanted to let you know the [Beta 0.7](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.7) adds this feature, enjoy. :)

**Comment by sonal-keshav** [comment]
Just tried it and it works great.

Just a quick nitpick: if no virtual desktops exist, and you use a shortcut (go to desktop 2, or move window to desktop 2), it does not create a desktop first.

Would it be technically possible to do that?

**Comment by sdias** [comment]
That's a good question. It might be possible, yeah. [There is another tool that has that feature](https://github.com/Eun/MoveToDesktop), but it hooks directly into the windows API, while I don't, since I just use [Ciantic's library](https://github.com/Ciantic/VirtualDesktopAccessor). If Ciantic's library supports it, I might be able to, but I can't say for sure right know.
