### ISSUE TITLE
Taskbar Scrolling Not Using Native Windows Transitions

### ISSUE THREAD

**Issue by thehoppster** [sdias/win-10-virtual-desktop-enhancer#104]
When using the taskbar scrolling feature, the native windows transitions are not present. They are present when using Ctrl + Windows Key + ( Left or Right Arrow) because I have my "UseNativePrevNextDesktopSwitchingIfConflicting" set to true. Is there any way to use the windows native desktop transitions while using the taskbar scrolling feature? I enjoy the scrolling taskbar greatly and the nice desktop transitions. It would be nice to see them work in unison. 

The native windows transitions also are not happening when moving a window from one desktop to another by using Ctrl + Windows Key + Shift + (Left or Right Arrow).

**Comment by GioBonvi** [comment]
Unfortunately there is no easy way to accomplish what you are asking: the only reasn that lets us have the transition with the `UseNativePrevNextDesktopSwitchingIfConflicting` is that when `Ctrl + Windows Key + (Left or Right Arrow)` is detected and that setting in active the keypress event is not intercepted by the script, but it's allowed to reach Windows directly (and since Windows is doing the desktop change we have the transition).  
Since scrolling on the taskbar does not trigger a desktop change in Windows 10 we have no event to let past our script and must force the change by ourself (which will not trigger the animation)
