### ISSUE TITLE
Don't set default bindings for "Switch" (they're already built into Windows!)

### ISSUE THREAD

**Issue by ErichDonGubler** [sdias/win-10-virtual-desktop-enhancer#13]
I suggest not setting the `Switch` shortcut by default.

As a power user of Chromium, my workflow got immediately interrupted as I found I couldn't use the `Alt + Arrow` shortcuts any more. There are other apps that can probably be listed that use `Alt + Arrow` also. which makes me think that the default isn't sensible. I see things this way: most people who are power users will find this default a clash with current flow, and most people who haven't used virtual desktops before probably won't have a reason to deviate from the normal `Ctrl + Win + Arrow` shortcut. Opinionated users (like those who favor Linux key bindings and `Ctrl + Alt + Arrow`) will probably be happy enough to change things themselves, since config is so simple.

Thoughts?

**Comment by ErichDonGubler** [comment]
Another example of somebody who's done something similar with a project that's very similar to this one: https://github.com/m0ngr31/VirtualDesktopManager/issues/15

**Comment by meffect** [comment]
meh

**Comment by sdias** [comment]
Thanks for the input.

Keyboard shortcuts for the switch action are only partially built into Windows. You can use `Ctrl + Win + Arrow` to switch to the previous/next desktops, but that is about it. You can't go to a specific desktop using the number keys, or move windows at all between desktops. A better solution would be to change the default for that setting to be `Switch=Win, Ctrl`, which would make it so the default windows kb shortcuts would still work, and the new shortcuts would be coherent with them since they would use the same modifiers.

I use `Switch=LAlt`, since it is what I find easiest and the most accessible. That is why it is the default. When I come across programs that require the use of `Alt`, I use `RAlt` instead, which isn't assigned to this app.

I definitely see your point though. I'm conflicted. I'll leave this open for feedback. If enough people want it changed, I'll change it.

**Comment by zhekaus** [comment]
The program is very helpful! However it must give an opportunity to set up hotkeys. Currently the program allows to switch between the desktops with ALT+CTRL+Number. However these shortcuts are using in many other programs, e.g. in MS Word for switching styles to H1-H3. It drives me crazy when I suddenly switch to another desktop trying simply to set Header2 style.

**Comment by sdias** [comment]
@zhekaus Hi. Thanks. You don't have to use the default hotkeys, you can change them under the `settings.ini` file. Please see the README for details.

**Comment by oskari** [comment]
I stumbled to the exact same problem with chrome and switched my 'switch' modified to 'Ctrl'. Now I can't use Ctrl + A to select all text.  Why does the program hijack shortcuts that it doesn't even use?

**Comment by drewnoakes** [comment]
@sdias I would vote for your idea of using <kbd>Ctrl</kbd>+<kbd>Win</kbd> as the default modifiers. The <kbd>Win</kbd> key makes it feel like you're operating at the desktop/shell level, and the pair is consistent with the built in (and not muscle-memorised) keys for switching desktops.

Right alt is not always an option in other programs. On my keyboard it's <kbd>Alt Gr</kbd> which doesn't  behave like an alt key.

**Comment by ErichDonGubler** [comment]
@drewnoakes I agree. Having a drop-in replacement with the keyboard shortcuts actually sounds really interesting for flow.

**Comment by sdias** [comment]
Ok, it seems that changing the defaults to something that resembles the default Windows keyboard shortcuts is the preferred option. I'll change the default switch combo to `Win`+`Ctrl`. What about moving windows across desktops? I'm thinking about setting move only to `Win`+`Shift` and move and shift to `Win`+`Shift`+`Ctrl`, which should be intuitive. What do you think?

**Comment by ErichDonGubler** [comment]
`Win`+`Shift`+`Ctrl` sounds pretty intuitive to me. That's my vote!

**Comment by meffect** [comment]
@oskari It does not do that to me. I think you have something else going on

**Comment by oskari** [comment]
@sdias @meffect Doesn't seem to do it always but there was definitely something going on as I didn't experience the issue anymore after I immediately closed virtual-desktop-enhancer.exe from taskbar.

**Comment by sdias** [comment]
@oskari AutoHotkey can bind keys in a lot of different ways. Maybe the one I'm using is not the most appropriate. I have noticed, for example, that when I switch desktops using `Alt`+`<Number>` into a desktop with a game running in windowed mode, my character crouches in the game, as if I had pressed `Ctrl`, which I don't think it makes a lot of sense and should not be happening, there may be something wrong with the implementation. I need to look into it.

**Comment by sdias** [comment]
[I just published a new release with the keyboard shortcuts that were suggested as defaults](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.0).
Unfortunately, there is a bug (that as far as I can tell I can't fix since it is due to an interaction between AutoHotkey and Windows) in that if certain keyboard shortcuts that use the `Windows` key are used, after using them the start menu opens. Due to that, the "move window and switch to desktop" action is now not set by default (since `Win + Shift` triggers this issue).

**Comment by meffect** [comment]
`MoveWindowAndSwitchToDesktop=Win, Shift` is working good for me. Start menu doesnt pop up. I'm on build [15025](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1703_.28Creators_Update.29_2) though.. maybe ms fixed something.  Love this update very cool ty all

**Comment by sdias** [comment]
@meffect Good to know, I might re-enable it in the future. Thanks.
