### ISSUE TITLE
Is it possible to use the num keypad for desktop switching

### ISSUE THREAD

**Issue by anxxx** [sdias/win-10-virtual-desktop-enhancer#18]
Hi - A really great app that fills a large gap in the default Windows setup.

I use a desktop keyboard and just wondered whether it would be possible to have an option to use the Num Keypad for the keyboard shortcuts rather than use the numbers above the keyboard.

As I am using, at your suggestion, Win, Ctrl with the arrow keys for moving right and left it seems a logical to move my right hand a fraction further to the right to use the Num Pad numbers for a particular desktop.

Many thanks in advance.

**Comment by sdias** [comment]
Hi. Thanks.

Yup, definitely agree with you. I prefer shortcuts that I can trigger with just my left hand, but, like you said, if the arrow keys based shortcuts already exist, I can't see a reason why numpad based shortcuts shouldn't also be a thing.

I'll try to address this in the next version.

**Comment by anxxx** [comment]
Thanks sdias

I realy appreciate the response and will look forward to the next version.

**Comment by romanrudenko** [comment]
Hi sdias,

I wanted to switch from using regular numbers to numpad /, * and - keys, and actually patched the main script to do this in a reasonably consistent manner. settings.ini gets another property (e.g. Desktops=NumpadDiv,NumpadMult,NumpadSub), and the main script uses those shortcuts if possible. Excess virtual displays revert to using numbers. I keep track of bound hotkeys, so that OnMoveNUmbered and their ilk can determine the screen number based on a hotkey.

If you want me to, I could clean up the code and provide it to you as a pull request. If you already wrote the similar functionality, stick to your stuff, as my AutoHotkey experience is a bit limited.

**Comment by sdias** [comment]
Hi @romanrudenko, 

Thanks for the suggestion, and I love how you've looked into patching my script to do what you want, that's awesome. 

As you probably can tell by the way the script was written, I really prefer switching between desktops using my left hand only (hence ALT+1, ALT+2, etc.). That was the main reason the Numpad was never considered for keyboard shortcuts before.

I do understand however that other people might enjoy using the Numpad, though. However, I would still like to implement something that works well with the other features that I already have in place. With that in mind, if I use the number keys on the Numpad to navigate between desktops instead of /, * and -, like you suggested, I can cover the first 20 desktops instead of just 6, and its usage is a lot more intuitive, since the number on the key will be the same as the desktop you navigate to (at least for the first 9 desktops). I would also like to keep those keys free for future features.

I do appreciate the suggestion and the offer though. Thanks.

**Comment by romanrudenko** [comment]
@sdias, thanks for the quick response. I know that you prefer the plain numbers. My implementation defaults to keeping plain numbers. They are replaced with something else only if a custom settings line is added to settings.ini. For me, this custom line is NumpadDiv, NumpadMult, NumpadSub. For someone who likes to use the numpad numbers, it would be Numpad1, Numpad2, ... , Numpad0. If one does not set custom hotkeys, the 1, 2,  ... , 0 defaults are still in effect.

Does this information change your willingness to consider the patch?

**Comment by sdias** [comment]
@romanrudenko I see. I guess I could add some additional optional keybindings for the first 3 desktops, it wouldn't be a lot of work. I don't like the idea of having them replace the original number key combinations, though. I'll try to get this into a future release. Don't worry about the PR though, I'd rather implement it myself, since the change is pretty simple.

**Comment by romanrudenko** [comment]
The rationale for replacing the original shortcuts is to allow native Win+# behavior of switching applications. If one uses Win modifier for virtual desktop switching, those shortcuts get clobbered. I could extend the code to give user a choice in the .ini - add custom shortcuts while keeping numbers, or replace the default number shortcuts.

In any case, you seem to be happier with doing things on your own. It is your project and your rules, so I respect that. Thank you for considering my request, and have fun building whatever you want it to be.

**Comment by sdias** [comment]
You have a point when you mention the native shortcuts. I'll give it some thought.

**Comment by sdias** [comment]
I'm a bit critical of some of the suggestions because I want to avoid bloating the script with features that are only useful for very particular situations or configurations.

@romanrudenko One way I could implement something that I think would satisfy your needs and be a bit more flexible would be to make the keys that represent the desktops completely customizable. They would default from 0-9, but you could change each to whatever you like. I might even provide a second set and set it by default to the number keys, that why I'd satisfy @anxxx's requirement as well. 

I'll probably implement that at some point.

**Comment by sdias** [comment]
@anxxx @romanrudenko [Check out the new release](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.1), I made it possible to customize desktop specific keyboard shortcuts, and there are two sets (that default to the regular number keys and the Numpad number keys).

**Comment by anxxx** [comment]
Just a quick note to say a huge thank you.

The new beta version seems to work perfectly with the Num Keys.

Greatly appreciated.

**Comment by sdias** [comment]
@anxxx No worries, happy to help. I'm glad you're enjoying it.
