### ISSUE TITLE
Wallpaper won't change; Only desktop 1 name working

### ISSUE THREAD

**Issue by boxler** [sdias/win-10-virtual-desktop-enhancer#43]
I can't get the wallpaper to change between desktops. I also cannot seem to get the Desktop name function to work beyond the first desktop. Any ideas as to what is causing this issue?

I copied and pasted the file location and filename.jpg next to the wallpaper section (1=, 2=)

**Comment by GioBonvi** [comment]
I have just downloaded this program and for me it works perfectly, so I really don't know why desktop names wouldn't work for you: maybe you could try dowloading it again making sure to use the [latest release](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/latest).

As for the wallpapers it could be usueful to know some more details: what does exactly happen? No wallpaper is shown? Some wallpaper are shown and others are not?    
If on one or more dekstops you see a black wallpaper instead of the image you have specified you probably have used an inexistent or wrong path in the configuration for that dekstop.

To get the path of a file right click on it > Properties > Copy the whole "Path" string, add a backslash "\" to the end and append the filename and extension to it.  
For example:
Path: `C:\Users\User\Images`  
Filename and extension: `wallpaper.jpg`  
Complete path: `C:\Users\User\Images\wallpaper.jpg`

You then have to put the _complete_ path of each wallpaper in the configuration file like this:  
```
[Wallpapers]
1=C:\Users\User1\Images\wallpaper1.jpg
2=C:\Users\User1\Images\wallpaper2.jpg
3=C:\Users\User2\Documents\wallpaper3.jpg
4=C:\Users\User2\Images\wallpaper4.jpg
...
``` 

Please note that if you leave one of the fields empty the wallpaper will not change when switching to that dekstop, maintaing the wallpaper from the previous desktop.
For example with this configuration file:
```
[Wallpapers]
1=C:\Users\User1\Images\wallpaper1.jpg
2=
3=C:\Users\User2\Documents\wallpaper3.jpg
...
```  
When switching to dekstop 2 from desktop 1 you will see desktop 1's wallpaper on dekstop 2, while when switching to dekstop 2 from desktop 3 you will see desktop 3's wallpaper on desktop 2.

I hope this helps you, if you need any help or have further questions related to this problem please ask them here.

**Comment by boxler** [comment]
Thank you for the feedback. I tried deleting and reinstalling the program and 2 of the wallpapers worked but not the others. However, I just deleted and reinstalled it a third time, but instead of putting the file in a folder, I put it directly on my desktop and now it seems to be working fine. The only issue I'm having now is the desktop names still do not work aside from the first desktop name. This isn't a big deal at all; I probably prefer using the names "desktop 1, desktop 2, etc." anyway after thinking about it. Thank you so much for your help once again!

**Comment by GioBonvi** [comment]
Maybe someone else will have some ideas: to me it sounds like a possible problem woth the pathnames of the wallpapers (non supported characters maybe, or something else). Hope you can sort it out.

**Comment by sdias** [comment]
Hi. Thanks @GioBonvi for the help. @boxler Not sure what is happening here, would you mind posting your `.ini` file?

**Comment by boxler** [comment]
This file?

By the way, desktop wallpapers are changing now. Just still having problems with the desktop names. After a fourth download attempt, I am up to 4 of the 5 desktop names showing up correctly. Can't seem to get them all to work, though.


; https://autohotkey.com/board/topic/33506-read-ini-file-in-one-go/

ReadIni( filename = 0 )
; Read a whole .ini file and creates variables like this:
; %Section%%Key% = %value%
{
Local s, c, p, key, k

	if not filename
		filename := SubStr( A_ScriptName, 1, -3 ) . "ini"

	FileRead, s, %filename%

	Loop, Parse, s, `n`r, %A_Space%%A_Tab%
	{
		c := SubStr(A_LoopField, 1, 1)
		if (c="[")
			key := SubStr(A_LoopField, 2, -1)
		else if (c=";")
			continue
		else {
			p := InStr(A_LoopField, "=")
			if p {
				k := SubStr(A_LoopField, 1, p-1)
				%key%%k% := SubStr(A_LoopField, p+1)
			}
		}
	}
}

**Comment by GioBonvi** [comment]
I think @sdias meant the `settings.ini` file, the one in the same folder as the executable.

**Comment by sdias** [comment]
I did indeed, sorry for not being clearer.

**Comment by GioBonvi** [comment]
Hi @boxler,  
are there any updates on the problems you reported?

**Comment by boxler** [comment]
I will send you the file contents next time I'm at my computer. Sorry for the delay. Everything works great except the names of the different desktops. This isn't a huge deal for me, however. Upon further consideration, I think I prefer the generic names of desktop 1, desktop 2, etc. Thanks for all the support with this :)

**Comment by boxler** [comment]
`[General]
DefaultDesktop=1
TaskbarScrollSwitching=1
UseNativePrevNextDesktopSwitchingIfConflicting=0

[Tooltips]
Enabled=1
Centered=1
FontSize=11
FontColor=0xFFFFFF
FontInBold=1
BackgroundColor=0x1F1F1F
Lifespan=750

[KeyboardShortcutsCombinations]
TogglePinWindow=Win, Ctrl, Shift, Q
TogglePinApp=Win, Ctrl, Shift, A
PinWindow=
PinApp=
UnpinWindow=
UnpinApp=
; "SC029" is the key below your "Esc" key
OpenDesktopManager=LAlt, SC029

[KeyboardShortcutsModifiers]
SwitchDesktop=Win, Ctrl
MoveWindowToDesktop=
MoveWindowAndSwitchToDesktop=Win, Ctrl, Shift
NextTenDesktops=

[KeyboardShortcutsIdentifiers]
PreviousDesktop=Left
NextDesktop=Right
Desktop1=1
Desktop2=2
Desktop3=3
Desktop4=4
Desktop5=5
Desktop6=6
Desktop7=7
Desktop8=8
Desktop9=9
Desktop10=0
DesktopAlt1=Numpad1
DesktopAlt2=Numpad2
DesktopAlt3=Numpad3
DesktopAlt4=Numpad4
DesktopAlt5=Numpad5
DesktopAlt6=Numpad6
DesktopAlt7=Numpad7
DesktopAlt8=Numpad8
DesktopAlt9=Numpad9
DesktopAlt10=Numpad0

[Wallpapers]
1=C:\Users\Brad\Desktop\Wallpapers\NeverStopLearning.jpg
2=C:\Users\Brad\Desktop\Wallpapers\brain.jpg
3=C:\Users\Brad\Desktop\Wallpapers\book.jpg
4=C:\Users\Brad\Desktop\Wallpapers\pvris.jpg
5=C:\Users\Brad\Desktop\Wallpapers\finland.jpg
6=
7=
8=
9=
10=

[DesktopNames]
1=Work
2=Calendar
3=Email
4=
Music
5=Games
6=
7=
8=
9=
10=

[RunProgramWhenSwitchingToDesktop]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[RunProgramWhenSwitchingFromDesktop]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=`

**Comment by boxler** [comment]
I figured out the problem upon posting my settings file here. There was a space or return between the equals sign and the beginning of the title to my 4th desktop. This did not show up on the file in notepad, however. After deleting this space, the title is displayed correctly.

Looks like everything is working appropriately now. Thank you all so much for your time and help in solving these issues. And thanks to the person who made this awesome program!

**Comment by GioBonvi** [comment]
Glad it all worked out!
