### ISSUE TITLE
How do you make custom changes?

### ISSUE THREAD

**Issue by dsutherland1492** [sdias/win-10-virtual-desktop-enhancer#53]
This seems to be mostly precompiled minus the the ahk file.  If you want to add functionality to the dll or update the exe for testing locally, how would you go about doing that?  Are you guys not planning posting all of the source code / build instructions?

**Comment by GioBonvi** [comment]
Hello, @dsutherland1492 

I am just a contributor here: @sdias is the creator of the project and he will surely be able to give you a better answer, however, from what I've understood since I've been helping here, this project uses a compiled DLL from [Ciantic's VirtualDesktopAccessor](https://github.com/Ciantic/VirtualDesktopAccessor) and I remember that someone said that it was compiled from [Grbacr07's VirtualDesktop](https://github.com/Grabacr07/VirtualDesktop) code.

So, if you want to have direct control over the DLL file, these two projects probably are what you are looking for.  
I hope this can help you.

Best regards

**Comment by dsutherland1492** [comment]
Oh sweet, that makes sense.  What about compiling the executable in the release?  Are you guys just converting the ahk file to an exe?  Or are you doing something fancier then that?

**Comment by GioBonvi** [comment]
Once again, releases are built by @sdias and not by me, however I believe in an old issue he mentioned "compiling the ahk script to match the last version", so almost certainly the exe file is actually nothing more than the compiled version of the ahk script.

**Comment by sdias** [comment]
@dsutherland1492 @GioBonvi I confirm everything that @GioBonvi has said, except for the fact that  [Ciantic's VirtualDesktopAccessor](https://github.com/Ciantic/VirtualDesktopAccessor) uses [Grbacr07's VirtualDesktop](https://github.com/Grabacr07/VirtualDesktop), that I'm not sure.

**Comment by GioBonvi** [comment]
@dsutherland1492 the comment I was referencing that I could not find before was one of mzomparelli's on #39.
