### ISSUE TITLE
Not working when run via task scheduler

### ISSUE THREAD

**Issue by janus0** [sdias/win-10-virtual-desktop-enhancer#75]
The program won't switch desktops or do anything else when I run this script via task scheduler with highest privileges. However, when I manually right click and do run as administrator, it works just fine. Thoughts?

**Comment by GioBonvi** [comment]
Hi @janus0!  
Thank you for reporting this.

I don't have time to thoroughly test this right now (will have in the next days); here is what I rapidly observed on my computer:

- if you follow [these instructions](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/installation.md#procedure-2-task-scheduler) to the letter Windows will automatically check "Do not run when running on battery" which in my case prevented the task from running. After removing this check in the task properties I was able to run the program with the task scheduler, however...
- If the task is run as the current user it will just load the green H icon in the taskbar without any functionalities.
- If the task is run as `SYSTEM` or as `Administrator` not even the green H icon will be loaded.

I don't remember if I actually had tested the Task Scheduler to autostart the program before, but it definitely does not work now for me neither.

Best regards

**Comment by janus0** [comment]
Is there any plan to fix this? I want to use task scheduler to launch virtual desktop enhancer on startup with administrator privileges without the annoying UAC prompt every time.

**Comment by GioBonvi** [comment]
I am currently working on this, but from what I can see right now there is little hope to make it work correctly...

May I ask why are you unable to use [the first procedure](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/installation.md#procedure-1-autostart-folder) which seems to work correctly?

Best

**Comment by janus0** [comment]
To my knowledge, the first procedure won't auto-start virtual desktop enhancer in administrator mode without me having to press "yes" on a UAC prompt every time I start my computer up. I need to run VDE in administrator mode because otherwise it won't switch desktops when I have a window focused which has admin privileges. Minor things, but it's what makes me current setup seamless and it's nice to have. Thanks!

**Comment by GioBonvi** [comment]
I see... Still no progress for me: reading some sources on the Internet it looks like it's not Autohotkey's problem, but something related to the code... I'll do my best to zero in on the problem.

At the moment I suspect this is strictly related to #21 and solving it would solve this.

**Comment by starise** [comment]
The problem should be caused by the fact that the tool needs to be launched from its working directory. When you create a shorcut (Procedure 1), Windows automatically fills the `Start in` directory (viewable into "properties > shortcut" tab).

On the other hand, when creating a scheduled task, you need to manually enter that directory filling the `Start in (optional):` box. It's working to me..

![Example](https://thumbs.gfycat.com/JampackedLegalAmoeba-size_restricted.gif)

**Comment by GioBonvi** [comment]
@starise 

You got it! I never noticed that option because in italian it has been horribly translated to "Inizio" (Which means "start", but definitely not "start in"...).

I'll update the documentation accordingly as soon as I can.

Thank you!

PS: @janus0 if you could confirm that this solves your problem this issue can be closed.

**Comment by keluecke** [comment]
I had this problem and solved it by creating and running this cmd script:

CD /d %~dp0
start virtual-desktop-enhancer.exe
