### ISSUE TITLE
No exe in zip file

### ISSUE THREAD

**Issue by Milad-jfr** [sdias/win-10-virtual-desktop-enhancer#84]
why there is no exe file in zip file ? how we can run this app ?

**Comment by GioBonvi** [comment]
Hello @Milad-jfr 

You probably have downloaded the source code instead of the release.  
Please make sure to follow the [installation instructions](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/installation.md) and download [the correct zip file](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/latest)

Let me know if you experience any further problem.
